services:
  rentacar:
    image: rentacar-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - database
    networks:
      - app
  
  database:
    image: postgres:latest
    container_name: rentacar-database
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app
  
  seq:
    image: datalust/seq
    container_name: rentacar-seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./containers/seq:/data
    ports:
      - 5341:5341
      - 80:80
    networks:
      - app

networks:
  app:
    driver: bridge