@HostAddress = http://localhost:8080/api/v1
@Token = <TOKEN>

### Login
POST {{HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "asd.asd123",
  "password": "asd123123"
}

### Create Vehicle
POST {{HostAddress}}/vehicles
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "make": "Ford",
  "model": "Mustang",
  "year": 2020,
  "fuelType": "petrol",
  "color": "brown"
}

### Update Vehicle
PUT {{HostAddress}}/vehicles/18
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "make": "Ford",
  "model": "Mustang",
  "year": 2020,
  "fuelType": "diesel",
  "color": "brown"
}

### Update Vehicle
DELETE {{HostAddress}}/vehicles/16
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Rent vehicle
POST {{HostAddress}}/rentals/19
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "startDate": "2060-06-25T22:44:33.302Z",
  "endDate": "2061-06-28T22:44:33.302Z"
}

### Cancel rent
DELETE {{HostAddress}}/rentals/22
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}