@HostAddress = http://localhost:8080/api/v1
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdC51c2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIzMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQyMzE4OTQ3LCJpc3MiOiJSZW50QUNhciIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC8ifQ.3vIPVk7nHoPdSzlZNH9rodADl38ZjCoM_tVeSsT28F0

### Register
POST {{HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "name": "Test User123",
  "username": "test.user123",
  "password": "testuser123123",
  "confirmPassword": "testuser123123"
}

### Login
POST {{HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "test.user",
  "password": "testuser123123"
}

### List vehicles
GET {{HostAddress}}/vehicles
Accept: application/json
Content-Type: application/json

### Create Vehicle [ADMIN]
POST {{HostAddress}}/vehicles
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "make": "Ford",
  "model": "Mustang",
  "year": 2020,
  "fuelType": "Petrol",
  "pricePerDay": 120,
  "color": "Brown"
}

### Update Vehicle [ADMIN]
PUT {{HostAddress}}/vehicles/18
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "make": "Ford",
  "model": "Mustang",
  "year": 2020,
  "fuelType": "diesel",
  "color": "brown"
}

### Update Vehicle [ADMIN]
DELETE {{HostAddress}}/vehicles/16
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Rent vehicle
POST {{HostAddress}}/rentals/27
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "startDate": "2055-05-31T22:44:33.302Z",
  "endDate": "2056-06-01T22:44:33.302Z",
  "couponCode": "mikemike"
}

### Cancel rent
DELETE {{HostAddress}}/rentals/42
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Create coupon [ADMIN]
POST {{HostAddress}}/coupons
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "code": "ASDXXX123",
  "description": "Get discout 50%",
  "discount": 50
}

### Change coupon active state [ADMIN]
PATCH {{HostAddress}}/coupons/6/toggle
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}