@HostAddress = http://localhost:8080/api/v1
@Token = <TOKEN>

### Register
POST {{HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "name": "Test User",
  "username": "test.user",
  "password": "testuser123123",
  "confirmPassword": "testuser123123"
}

### Login
POST {{HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "test.user",
  "password": "testuser123123"
}

### Create Vehicle [ADMIN]
POST {{HostAddress}}/vehicles
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "make": "Ford",
  "model": "Mustang",
  "year": 2020,
  "fuelType": "Petrol",
  "pricePerDay": 120,
  "color": "Brown"
}

### Update Vehicle [ADMIN]
PUT {{HostAddress}}/vehicles/18
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "make": "Ford",
  "model": "Mustang",
  "year": 2020,
  "fuelType": "diesel",
  "color": "brown"
}

### Update Vehicle [ADMIN]
DELETE {{HostAddress}}/vehicles/16
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Rent vehicle
POST {{HostAddress}}/rentals/22
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "startDate": "2055-05-31T22:44:33.302Z",
  "endDate": "2056-06-01T22:44:33.302Z"
}

### Cancel rent
DELETE {{HostAddress}}/rentals/42
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Create coupon [ADMIN]
POST {{HostAddress}}/coupons
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "code": "ASDXXX123",
  "description": "Get discout 50%",
  "discount": 50
}

### Change coupon active state [ADMIN]
PATCH {{HostAddress}}/coupons/6/toggle
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}